// The lesson material: N5-ish vocabulary, the 46 basic hiragana, and
// particle sentences in the spirit of Cure Dolly (each one has exactly one
// grammatical answer among its four options).

export type Word = { jp: string; kana: string; en: string }
export type Kana = { kana: string; romaji: string }
export type Particle = { before: string; after: string; answer: string; options: string[]; en: string; why: string }

export const WORDS: Word[] = [
  { jp: '猫', kana: 'ねこ', en: 'cat' },
  { jp: '犬', kana: 'いぬ', en: 'dog' },
  { jp: '水', kana: 'みず', en: 'water' },
  { jp: '本', kana: 'ほん', en: 'book' },
  { jp: '山', kana: 'やま', en: 'mountain' },
  { jp: '川', kana: 'かわ', en: 'river' },
  { jp: '花', kana: 'はな', en: 'flower' },
  { jp: '魚', kana: 'さかな', en: 'fish' },
  { jp: '鳥', kana: 'とり', en: 'bird' },
  { jp: '空', kana: 'そら', en: 'sky' },
  { jp: '雨', kana: 'あめ', en: 'rain' },
  { jp: '雪', kana: 'ゆき', en: 'snow' },
  { jp: '月', kana: 'つき', en: 'moon' },
  { jp: '火', kana: 'ひ', en: 'fire' },
  { jp: '木', kana: 'き', en: 'tree' },
  { jp: '石', kana: 'いし', en: 'stone' },
  { jp: '海', kana: 'うみ', en: 'sea' },
  { jp: '星', kana: 'ほし', en: 'star' },
  { jp: '桜', kana: 'さくら', en: 'cherry blossom' },
  { jp: '夜', kana: 'よる', en: 'night' },
  { jp: '朝', kana: 'あさ', en: 'morning' },
  { jp: '夢', kana: 'ゆめ', en: 'dream' },
  { jp: '人', kana: 'ひと', en: 'person' },
  { jp: '友達', kana: 'ともだち', en: 'friend' },
  { jp: '先生', kana: 'せんせい', en: 'teacher' },
  { jp: '学生', kana: 'がくせい', en: 'student' },
  { jp: '学校', kana: 'がっこう', en: 'school' },
  { jp: '電車', kana: 'でんしゃ', en: 'train' },
  { jp: '車', kana: 'くるま', en: 'car' },
  { jp: '家', kana: 'いえ', en: 'house' },
  { jp: '駅', kana: 'えき', en: 'station' },
  { jp: '店', kana: 'みせ', en: 'shop' },
  { jp: '部屋', kana: 'へや', en: 'room' },
  { jp: '窓', kana: 'まど', en: 'window' },
  { jp: '机', kana: 'つくえ', en: 'desk' },
  { jp: '傘', kana: 'かさ', en: 'umbrella' },
  { jp: '靴', kana: 'くつ', en: 'shoes' },
  { jp: '時計', kana: 'とけい', en: 'clock' },
  { jp: '電話', kana: 'でんわ', en: 'telephone' },
  { jp: '画面', kana: 'がめん', en: 'screen' },
  { jp: 'お茶', kana: 'おちゃ', en: 'tea' },
  { jp: 'ご飯', kana: 'ごはん', en: 'rice / meal' },
  { jp: '肉', kana: 'にく', en: 'meat' },
  { jp: '卵', kana: 'たまご', en: 'egg' },
  { jp: '食べる', kana: 'たべる', en: 'to eat' },
  { jp: '飲む', kana: 'のむ', en: 'to drink' },
  { jp: '見る', kana: 'みる', en: 'to see' },
  { jp: '行く', kana: 'いく', en: 'to go' },
  { jp: '来る', kana: 'くる', en: 'to come' },
  { jp: '読む', kana: 'よむ', en: 'to read' },
  { jp: '書く', kana: 'かく', en: 'to write' },
  { jp: '話す', kana: 'はなす', en: 'to speak' },
  { jp: '聞く', kana: 'きく', en: 'to listen' },
  { jp: '寝る', kana: 'ねる', en: 'to sleep' },
  { jp: '大きい', kana: 'おおきい', en: 'big' },
  { jp: '小さい', kana: 'ちいさい', en: 'small' },
  { jp: '新しい', kana: 'あたらしい', en: 'new' },
  { jp: '古い', kana: 'ふるい', en: 'old' },
  { jp: '安い', kana: 'やすい', en: 'cheap' },
  { jp: '寒い', kana: 'さむい', en: 'cold (weather)' },
  { jp: '暑い', kana: 'あつい', en: 'hot (weather)' },
  { jp: '好き', kana: 'すき', en: 'liked' },
]

export const HIRAGANA: Kana[] = [
  ['あ', 'a'], ['い', 'i'], ['う', 'u'], ['え', 'e'], ['お', 'o'],
  ['か', 'ka'], ['き', 'ki'], ['く', 'ku'], ['け', 'ke'], ['こ', 'ko'],
  ['さ', 'sa'], ['し', 'shi'], ['す', 'su'], ['せ', 'se'], ['そ', 'so'],
  ['た', 'ta'], ['ち', 'chi'], ['つ', 'tsu'], ['て', 'te'], ['と', 'to'],
  ['な', 'na'], ['に', 'ni'], ['ぬ', 'nu'], ['ね', 'ne'], ['の', 'no'],
  ['は', 'ha'], ['ひ', 'hi'], ['ふ', 'fu'], ['へ', 'he'], ['ほ', 'ho'],
  ['ま', 'ma'], ['み', 'mi'], ['む', 'mu'], ['め', 'me'], ['も', 'mo'],
  ['や', 'ya'], ['ゆ', 'yu'], ['よ', 'yo'],
  ['ら', 'ra'], ['り', 'ri'], ['る', 'ru'], ['れ', 're'], ['ろ', 'ro'],
  ['わ', 'wa'], ['を', 'wo'], ['ん', 'n'],
].map(([kana, romaji]) => ({ kana: kana as string, romaji: romaji as string }))

export const PARTICLES: Particle[] = [
  { before: 'わたし', after: 'がくせいです。', answer: 'は', options: ['は', 'を', 'に', 'で'], en: 'I am a student.', why: 'は sets the topic: "as for me…"' },
  { before: 'ねこ', after: 'すきです。', answer: 'が', options: ['が', 'を', 'に', 'で'], en: 'I like cats.', why: 'すき is an adjective; the thing liked takes が' },
  { before: 'みず', after: 'のみます。', answer: 'を', options: ['を', 'に', 'で', 'の'], en: 'I drink water.', why: 'を marks what the action is done to' },
  { before: 'がっこう', after: 'いきます。', answer: 'に', options: ['に', 'を', 'の', 'と'], en: 'I go to school.', why: 'に marks the destination' },
  { before: 'としょかん', after: 'ほんをよみます。', answer: 'で', options: ['で', 'を', 'に', 'へ'], en: 'I read books at the library.', why: 'で marks where an action happens' },
  { before: 'わたし', after: 'ほんです。', answer: 'の', options: ['の', 'を', 'に', 'で'], en: 'It is my book.', why: 'の links nouns: "my book"' },
  { before: 'ともだち', after: 'えいがをみます。', answer: 'と', options: ['と', 'を', 'へ', 'に'], en: 'I watch a movie with a friend.', why: 'と means "together with"' },
  { before: '７じ', after: 'おきます。', answer: 'に', options: ['に', 'で', 'を', 'の'], en: 'I wake up at 7.', why: 'に marks a specific time' },
  { before: 'だれ', after: 'きましたか。', answer: 'が', options: ['が', 'は', 'を', 'に'], en: 'Who came?', why: 'question words never take は; they take が' },
  { before: 'にほんご', after: 'べんきょうします。', answer: 'を', options: ['を', 'に', 'へ', 'の'], en: 'I study Japanese.', why: 'を marks the thing studied' },
  { before: 'はし', after: 'たべます。', answer: 'で', options: ['で', 'に', 'へ', 'の'], en: 'I eat with chopsticks.', why: 'で marks the means or tool' },
  { before: 'へや', after: 'ねこがいます。', answer: 'に', options: ['に', 'を', 'で', 'へ'], en: 'There is a cat in the room.', why: 'いる / ある take に for where something exists' },
  { before: 'あめ', after: 'ふっています。', answer: 'が', options: ['が', 'を', 'に', 'で'], en: 'It is raining.', why: 'が marks the doer of ふる' },
  { before: 'とうきょう', after: 'すんでいます。', answer: 'に', options: ['に', 'を', 'で', 'と'], en: 'I live in Tokyo.', why: 'すむ takes に, not で' },
  { before: 'にほん', after: 'きました。', answer: 'から', options: ['から', 'を', 'で', 'の'], en: 'I came from Japan.', why: 'から means "from"' },
  { before: 'これ', after: 'なんですか。', answer: 'は', options: ['は', 'を', 'に', 'で'], en: 'What is this?', why: 'は makes これ the topic' },
]
